// Code generated by MockGen. DO NOT EDIT.
// Source: actor.go

// Package repo is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/ilyushkaaa/Filmoteka/internal/actors/entity"
	dto "github.com/ilyushkaaa/Filmoteka/internal/dto"
)

// MockActorRepo is a mock of ActorRepo interface.
type MockActorRepo struct {
	ctrl     *gomock.Controller
	recorder *MockActorRepoMockRecorder
}

// MockActorRepoMockRecorder is the mock recorder for MockActorRepo.
type MockActorRepoMockRecorder struct {
	mock *MockActorRepo
}

// NewMockActorRepo creates a new mock instance.
func NewMockActorRepo(ctrl *gomock.Controller) *MockActorRepo {
	mock := &MockActorRepo{ctrl: ctrl}
	mock.recorder = &MockActorRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActorRepo) EXPECT() *MockActorRepoMockRecorder {
	return m.recorder
}

// AddActor mocks base method.
func (m *MockActorRepo) AddActor(actor entity.Actor) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddActor", actor)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddActor indicates an expected call of AddActor.
func (mr *MockActorRepoMockRecorder) AddActor(actor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddActor", reflect.TypeOf((*MockActorRepo)(nil).AddActor), actor)
}

// DeleteActor mocks base method.
func (m *MockActorRepo) DeleteActor(ID uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActor", ID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteActor indicates an expected call of DeleteActor.
func (mr *MockActorRepoMockRecorder) DeleteActor(ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActor", reflect.TypeOf((*MockActorRepo)(nil).DeleteActor), ID)
}

// GetActorByID mocks base method.
func (m *MockActorRepo) GetActorByID(actorID uint64) (*dto.ActorWithFilms, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorByID", actorID)
	ret0, _ := ret[0].(*dto.ActorWithFilms)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActorByID indicates an expected call of GetActorByID.
func (mr *MockActorRepoMockRecorder) GetActorByID(actorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorByID", reflect.TypeOf((*MockActorRepo)(nil).GetActorByID), actorID)
}

// GetActors mocks base method.
func (m *MockActorRepo) GetActors() ([]dto.ActorWithFilms, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActors")
	ret0, _ := ret[0].([]dto.ActorWithFilms)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActors indicates an expected call of GetActors.
func (mr *MockActorRepoMockRecorder) GetActors() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActors", reflect.TypeOf((*MockActorRepo)(nil).GetActors))
}

// UpdateActor mocks base method.
func (m *MockActorRepo) UpdateActor(actor entity.Actor) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActor", actor)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateActor indicates an expected call of UpdateActor.
func (mr *MockActorRepoMockRecorder) UpdateActor(actor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActor", reflect.TypeOf((*MockActorRepo)(nil).UpdateActor), actor)
}
