// Code generated by MockGen. DO NOT EDIT.
// Source: film.go

// Package usecase is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/ilyushkaaa/Filmoteka/internal/films/entity"
)

// MockFilmUseCase is a mock of FilmUseCase interface.
type MockFilmUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockFilmUseCaseMockRecorder
}

// MockFilmUseCaseMockRecorder is the mock recorder for MockFilmUseCase.
type MockFilmUseCaseMockRecorder struct {
	mock *MockFilmUseCase
}

// NewMockFilmUseCase creates a new mock instance.
func NewMockFilmUseCase(ctrl *gomock.Controller) *MockFilmUseCase {
	mock := &MockFilmUseCase{ctrl: ctrl}
	mock.recorder = &MockFilmUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilmUseCase) EXPECT() *MockFilmUseCaseMockRecorder {
	return m.recorder
}

// AddFilm mocks base method.
func (m *MockFilmUseCase) AddFilm(film entity.Film, actorIDs []uint64) (*entity.Film, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFilm", film, actorIDs)
	ret0, _ := ret[0].(*entity.Film)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddFilm indicates an expected call of AddFilm.
func (mr *MockFilmUseCaseMockRecorder) AddFilm(film, actorIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFilm", reflect.TypeOf((*MockFilmUseCase)(nil).AddFilm), film, actorIDs)
}

// DeleteFilm mocks base method.
func (m *MockFilmUseCase) DeleteFilm(ID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFilm", ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFilm indicates an expected call of DeleteFilm.
func (mr *MockFilmUseCaseMockRecorder) DeleteFilm(ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFilm", reflect.TypeOf((*MockFilmUseCase)(nil).DeleteFilm), ID)
}

// GetFilmByID mocks base method.
func (m *MockFilmUseCase) GetFilmByID(filmID uint64) (*entity.Film, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmByID", filmID)
	ret0, _ := ret[0].(*entity.Film)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmByID indicates an expected call of GetFilmByID.
func (mr *MockFilmUseCaseMockRecorder) GetFilmByID(filmID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmByID", reflect.TypeOf((*MockFilmUseCase)(nil).GetFilmByID), filmID)
}

// GetFilms mocks base method.
func (m *MockFilmUseCase) GetFilms(sortParam string) ([]entity.Film, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilms", sortParam)
	ret0, _ := ret[0].([]entity.Film)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilms indicates an expected call of GetFilms.
func (mr *MockFilmUseCaseMockRecorder) GetFilms(sortParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilms", reflect.TypeOf((*MockFilmUseCase)(nil).GetFilms), sortParam)
}

// GetFilmsBySearch mocks base method.
func (m *MockFilmUseCase) GetFilmsBySearch(searchStr string) ([]entity.Film, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilmsBySearch", searchStr)
	ret0, _ := ret[0].([]entity.Film)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilmsBySearch indicates an expected call of GetFilmsBySearch.
func (mr *MockFilmUseCaseMockRecorder) GetFilmsBySearch(searchStr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilmsBySearch", reflect.TypeOf((*MockFilmUseCase)(nil).GetFilmsBySearch), searchStr)
}

// UpdateFilm mocks base method.
func (m *MockFilmUseCase) UpdateFilm(film entity.Film, actorIDs []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFilm", film, actorIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFilm indicates an expected call of UpdateFilm.
func (mr *MockFilmUseCaseMockRecorder) UpdateFilm(film, actorIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFilm", reflect.TypeOf((*MockFilmUseCase)(nil).UpdateFilm), film, actorIDs)
}
